### PR TITLE
Better Vector2

### PR DESCRIPTION
**Pull request by iacore**
with this change, I don't thing `Vector2.set_x` is necessary any more

### CODE REVIEW

**Comment by iacore** [comment]
I have made a library with F32. Maybe you can use it?
https://git.envs.net/iacore/lean-primitives

It's encoded as `u32` by Lean.

**Comment by KislyjKisel** [comment]
Thanks for the pr! Sorry for not replying sooner.

It seems that the example in `Main.lean` broke (`Vector2.x` and `Vector2.y` always return 0, idk why).
Perhaps it would be better to use fully Lean's definition of vectors (without `extern` attributes) and change the C code using it, instead of using an "external" object. This would require a lot of changes in ffi though.

> I don't thing `Vector2.set_x` is necessary any more

Definitely.

> I have made a library with F32. Maybe you can use it?

I think it is better to keep using `Float` because it is a built-in. There are already multiple cases in this library where `int` is translated as `UInt32` for convenience (where appropriate, e.g. sizes).

**Comment by iacore** [comment]
> It seems that the example in Main.lean broke (Vector2.x and Vector2.y always return 0, idk why).

It works for me. (I tried `Repr.repr (Vector2.mk 1 2)`). Derived interface code is broken (it uses the Lean definition of types instead of FFI).

> I think it is better to keep using Float because it is a built-in. There are already multiple cases in this library where int is translated as UInt32 for convenience (where appropriate, e.g. sizes).

`Float` is `f64`. Type conversion takes time. Lean's FFI is still experimental. Depends on how much time you want to put into developing this library.

**Comment by KislyjKisel** [comment]
> It works for me.

Part of the generated code for `Main`:
```C
x_40 = lean_raylib__GetMousePosition(x_39);
x_41 = lean_ctor_get(x_40, 0);
lean_inc(x_41);
x_42 = lean_ctor_get(x_40, 1);
```
(note: `GetMousePosition` uses `lean_alloc_external`)
I suspect that `extern` might not work with auto-generated constructors and getters.

The following code doesn't use `lean_raylib__Vector2_...` when translated:
```Lean
let tea := Vector2.mk 1.0 2.0
IO.println $ repr tea
```

> Type conversion takes time. Lean's FFI is still experimental.

As long as that's the case, I don't mind the performance penalty.

**Comment by iacore** [comment]
> The following code doesn't use `lean_raylib__Vector2_...` when translated:

Lean optimization is free to reorganize the code according to the declared code. In other words, it doesn't care about `implemented_by` or `extern` when folding your code.

**Comment by KislyjKisel** [comment]
I've started moving pod definitions to Lean side so the pr is now obsolete.

**Pull request closed without merging**
